//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.ADIM.OA.WebUI.WorkFlow.Receive {
    
    
    public partial class UC_CompanyReceive {
        
        /// <summary>
        /// tblPlot 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable tblPlot;
        
        /// <summary>
        /// txtLeaderComment 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtLeaderComment;
        
        /// <summary>
        /// btnComplete 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnComplete;
        
        /// <summary>
        /// btnInstructionSave 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnInstructionSave;
        
        /// <summary>
        /// FormPanel 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel FormPanel;
        
        /// <summary>
        /// txtReceiveNo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtReceiveNo;
        
        /// <summary>
        /// txtReceiveDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtReceiveDate;
        
        /// <summary>
        /// txtSendLetterNo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtSendLetterNo;
        
        /// <summary>
        /// txtCommunicationUnit 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCommunicationUnit;
        
        /// <summary>
        /// txtPreVolumeNo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtPreVolumeNo;
        
        /// <summary>
        /// txtDocumentTitle 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtDocumentTitle;
        
        /// <summary>
        /// ddlOfficer 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSDropDownList ddlOfficer;
        
        /// <summary>
        /// lbOfficer 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbOfficer;
        
        /// <summary>
        /// txtOfficerComment 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtOfficerComment;
        
        /// <summary>
        /// ddlLeadShip 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSDropDownList ddlLeadShip;
        
        /// <summary>
        /// lbLeadShip 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbLeadShip;
        
        /// <summary>
        /// txtLeadCommentView 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtLeadCommentView;
        
        /// <summary>
        /// lblDeptOrPeoplr 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDeptOrPeoplr;
        
        /// <summary>
        /// txtUnderTakeDeptName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtUnderTakeDeptName;
        
        /// <summary>
        /// OASelectUC1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageOU.UC_OASelect OASelectUC1;
        
        /// <summary>
        /// txtUnderTakeUserName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtUnderTakeUserName;
        
        /// <summary>
        /// OASelectUC2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageOU.UC_OASelect OASelectUC2;
        
        /// <summary>
        /// txtUnderTakeComment 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtUnderTakeComment;
        
        /// <summary>
        /// txtPrompt 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtPrompt;
        
        /// <summary>
        /// txtPromptEdit 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtPromptEdit;
        
        /// <summary>
        /// ucAttachment 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageWF.UC_FileControl ucAttachment;
        
        /// <summary>
        /// ucCommentList 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageWF.UC_CommentList ucCommentList;
        
        /// <summary>
        /// divCirculates 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCirculates;
        
        /// <summary>
        /// txtCirculateDeptName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtCirculateDeptName;
        
        /// <summary>
        /// txtCirculatePeopleName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtCirculatePeopleName;
        
        /// <summary>
        /// ucCirculatePeople 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageOU.UC_OASelect ucCirculatePeople;
        
        /// <summary>
        /// divUndertake 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divUndertake;
        
        /// <summary>
        /// td1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell td1;
        
        /// <summary>
        /// lbldept 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbldept;
        
        /// <summary>
        /// dllUnderDept 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSDropDownList dllUnderDept;
        
        /// <summary>
        /// lblmember 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblmember;
        
        /// <summary>
        /// ddlUnderPeople 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSDropDownList ddlUnderPeople;
        
        /// <summary>
        /// txtUnderComment 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtUnderComment;
        
        /// <summary>
        /// btnDistribute 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnDistribute;
        
        /// <summary>
        /// btnGuiDang 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnGuiDang;
        
        /// <summary>
        /// btnCommon1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnCommon1;
        
        /// <summary>
        /// btnCommon2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnCommon2;
        
        /// <summary>
        /// btnCommon3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnCommon3;
        
        /// <summary>
        /// btnCommon4 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnCommon4;
        
        /// <summary>
        /// btnCommon5 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnCommon5;
        
        /// <summary>
        /// ucPrint 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageWF.UC_Print ucPrint;
        
        /// <summary>
        /// txtUnderTakeDeptID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtUnderTakeDeptID;
        
        /// <summary>
        /// txtDrafter 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtDrafter;
        
        /// <summary>
        /// txtDraftDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtDraftDate;
        
        /// <summary>
        /// txtUnderTakeUserID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtUnderTakeUserID;
        
        /// <summary>
        /// txtCurrStep 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtCurrStep;
        
        /// <summary>
        /// txtCSUnderUserID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtCSUnderUserID;
        
        /// <summary>
        /// txtCdeptID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtCdeptID;
        
        /// <summary>
        /// txtCPeopleID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtCPeopleID;
        
        /// <summary>
        /// txtJinJi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtJinJi;
    }
}
