//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.ADIM.OA.WebUI.WorkFlow.RequestReport {
    
    
    public partial class UC_RequestReport {
        
        /// <summary>
        /// ddlType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSDropDownList ddlType;
        
        /// <summary>
        /// lblNiGaoRiQi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblNiGaoRiQi;
        
        /// <summary>
        /// ddlZhuSong 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSDropDownList ddlZhuSong;
        
        /// <summary>
        /// txtBianHao 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtBianHao;
        
        /// <summary>
        /// ddlBianZhiBuMen 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSDropDownList ddlBianZhiBuMen;
        
        /// <summary>
        /// txtChaoSong 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChaoSong;
        
        /// <summary>
        /// OASelectUC1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageOU.UC_OASelect OASelectUC1;
        
        /// <summary>
        /// txtZhuTi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtZhuTi;
        
        /// <summary>
        /// txtNeiRong 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtNeiRong;
        
        /// <summary>
        /// txtLingDaoPiShi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtLingDaoPiShi;
        
        /// <summary>
        /// txtChengBanBuMen 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChengBanBuMen;
        
        /// <summary>
        /// OASelectUC5 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageOU.UC_OASelect OASelectUC5;
        
        /// <summary>
        /// txtChuLiYiJian 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChuLiYiJian;
        
        /// <summary>
        /// TrBanLiYiJian 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow TrBanLiYiJian;
        
        /// <summary>
        /// txtBanLiYiJian 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtBanLiYiJian;
        
        /// <summary>
        /// TrChenBan 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow TrChenBan;
        
        /// <summary>
        /// txtBuMenLingDao 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtBuMenLingDao;
        
        /// <summary>
        /// lblDirector 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDirector;
        
        /// <summary>
        /// ddlKeShiLingDao 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSDropDownList ddlKeShiLingDao;
        
        /// <summary>
        /// lblSection 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSection;
        
        /// <summary>
        /// ddlChengBanRen 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSDropDownList ddlChengBanRen;
        
        /// <summary>
        /// lblMember 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMember;
        
        /// <summary>
        /// txtChengBanRiQi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChengBanRiQi;
        
        /// <summary>
        /// TrChuanYue 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow TrChuanYue;
        
        /// <summary>
        /// txtChuanYueRenYuan 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChuanYueRenYuan;
        
        /// <summary>
        /// OASelectUC2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageOU.UC_OASelect OASelectUC2;
        
        /// <summary>
        /// TaTishi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable TaTishi;
        
        /// <summary>
        /// txtTiShiXinXi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtTiShiXinXi;
        
        /// <summary>
        /// txtTianJia 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtTianJia;
        
        /// <summary>
        /// ddlFuZeRen 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSDropDownList ddlFuZeRen;
        
        /// <summary>
        /// lbLeader 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbLeader;
        
        /// <summary>
        /// txtHeGaoRen 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtHeGaoRen;
        
        /// <summary>
        /// OASelectUC3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageOU.UC_OASelect OASelectUC3;
        
        /// <summary>
        /// lbHeGaoRen 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbHeGaoRen;
        
        /// <summary>
        /// txtNiGaoRen 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtNiGaoRen;
        
        /// <summary>
        /// lbNiGaoRen 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbNiGaoRen;
        
        /// <summary>
        /// txtQianFaRiQi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtQianFaRiQi;
        
        /// <summary>
        /// lbQianFaRiQi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbQianFaRiQi;
        
        /// <summary>
        /// tbChuanYue 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable tbChuanYue;
        
        /// <summary>
        /// txtDeptName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtDeptName;
        
        /// <summary>
        /// txtUserName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtUserName;
        
        /// <summary>
        /// OASelectUC4 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageOU.UC_OASelect OASelectUC4;
        
        /// <summary>
        /// hDeptID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hDeptID;
        
        /// <summary>
        /// hUserID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hUserID;
        
        /// <summary>
        /// ucAttachment 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageWF.UC_FileControl ucAttachment;
        
        /// <summary>
        /// btnChengBanFenFa 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnChengBanFenFa;
        
        /// <summary>
        /// btnTongGuoShenHe 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnTongGuoShenHe;
        
        /// <summary>
        /// btnLingDaoPiShi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnLingDaoPiShi;
        
        /// <summary>
        /// btnZhuRenShenHe 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnZhuRenShenHe;
        
        /// <summary>
        /// btnFenFa 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnFenFa;
        
        /// <summary>
        /// btnTiJiaoQianFa 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnTiJiaoQianFa;
        
        /// <summary>
        /// btnTiJiaoHeGao 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnTiJiaoHeGao;
        
        /// <summary>
        /// btnTuiHui 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnTuiHui;
        
        /// <summary>
        /// btnCancel 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnCancel;
        
        /// <summary>
        /// btnSave 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnSave;
        
        /// <summary>
        /// btnJiaoBanKeshi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnJiaoBanKeshi;
        
        /// <summary>
        /// btnJiaoBanRenYuan 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnJiaoBanRenYuan;
        
        /// <summary>
        /// btnWanCheng 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnWanCheng;
        
        /// <summary>
        /// btnZhuiJiaFenFa 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnZhuiJiaFenFa;
        
        /// <summary>
        /// btnWanChengGuiDang 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnWanChengGuiDang;
        
        /// <summary>
        /// btn_GuiDang 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btn_GuiDang;
        
        /// <summary>
        /// ucPrint 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageWF.UC_Print ucPrint;
        
        /// <summary>
        /// TdYiJian 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell TdYiJian;
        
        /// <summary>
        /// txtBanShuiXinXi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtBanShuiXinXi;
        
        /// <summary>
        /// txtPiShiYiJian 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtPiShiYiJian;
        
        /// <summary>
        /// btnComplete 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnComplete;
        
        /// <summary>
        /// btnSavePishi 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnSavePishi;
        
        /// <summary>
        /// txtIsBack 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtIsBack;
        
        /// <summary>
        /// txtZhuSongID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtZhuSongID;
        
        /// <summary>
        /// txtChaoSongID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChaoSongID;
        
        /// <summary>
        /// txtChaoSongDeptID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChaoSongDeptID;
        
        /// <summary>
        /// txtChaoSongUserID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChaoSongUserID;
        
        /// <summary>
        /// txtNiGaoRenID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtNiGaoRenID;
        
        /// <summary>
        /// txtHeGaoRenID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtHeGaoRenID;
        
        /// <summary>
        /// txtKeShiLingDaoID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtKeShiLingDaoID;
        
        /// <summary>
        /// txtKeShiLingDao 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtKeShiLingDao;
        
        /// <summary>
        /// txtChengBanRen 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChengBanRen;
        
        /// <summary>
        /// txtChengBanRenID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChengBanRenID;
        
        /// <summary>
        /// txtChengBanBuMenID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChengBanBuMenID;
        
        /// <summary>
        /// txtChuanYueRenIDs 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChuanYueRenIDs;
        
        /// <summary>
        /// txtChuanYueDeptIDs 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtChuanYueDeptIDs;
        
        /// <summary>
        /// txtBuMenLingDaoID 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtBuMenLingDaoID;
        
        /// <summary>
        /// txtRequestCategory 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtRequestCategory;
        
        /// <summary>
        /// lbJs 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbJs;
    }
}
