//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.ADIM.OA.WebUI.WorkFlow.Receive.ReDetail {
    
    
    public partial class UC_HSReDetail {
        
        /// <summary>
        /// txtReceiveUnit 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtReceiveUnit;
        
        /// <summary>
        /// txtDocumentTitle 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtDocumentTitle;
        
        /// <summary>
        /// txtDocumentNo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtDocumentNo;
        
        /// <summary>
        /// txtDocumentEncoding 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtDocumentEncoding;
        
        /// <summary>
        /// txtReceiveDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtReceiveDate;
        
        /// <summary>
        /// txtReplyDocumentNo 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtReplyDocumentNo;
        
        /// <summary>
        /// txtOtherEncoding 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtOtherEncoding;
        
        /// <summary>
        /// txtXingWenDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtXingWenDate;
        
        /// <summary>
        /// txtDocumentType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtDocumentType;
        
        /// <summary>
        /// txtFormationDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtFormationDate;
        
        /// <summary>
        /// txtUrgentDegree 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtUrgentDegree;
        
        /// <summary>
        /// txtPageCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtPageCount;
        
        /// <summary>
        /// txtKeepTime 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtKeepTime;
        
        /// <summary>
        /// txtContractNumber 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtContractNumber;
        
        /// <summary>
        /// txtEquipmentCode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtEquipmentCode;
        
        /// <summary>
        /// txtHNCode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtHNCode;
        
        /// <summary>
        /// txtRemark 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSTextBox txtRemark;
        
        /// <summary>
        /// ucAttachment 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FS.ADIM.OA.WebUI.PageWF.UC_FileControl ucAttachment;
        
        /// <summary>
        /// divPrompt 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPrompt;
        
        /// <summary>
        /// rptProcessDetail 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptProcessDetail;
        
        /// <summary>
        /// gdvCirculate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSGridView gdvCirculate;
        
        /// <summary>
        /// btnReturn 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::FounderSoftware.Framework.UI.WebCtrls.FSButton btnReturn;
    }
}
